remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll

title:              Hyeoni's Blog
email:              gusk743@gmail.com
description:        Step By Step ğŸƒâ€
author:             hyeoni90
baseurl:            ""
url:                "https://hyeoni90.github.io"

# Social Profiles
github_username:    hyeoni90

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
